### ISSUE TITLE
显示视频发布时间

### ISSUE THREAD

**Issue by 123shn** [douyin-helper/douyin-helper#20]
### Discussed in https://github.com/douyin-helper/douyin-helper/discussions/2

<div type='discussions-op-text'>

<sup>Originally posted by **wildseeder** January 11, 2022</sup>
有时候会刷到一些已经过时了的旧闻，而现在推荐流里并没有显示视频发布时间，加上这个信息可以使上下文更完整。

在发布者名称显示位置的后面加上“发布于 X 天前”等字样比较合适。</div>

**Comment by wildseeder** [comment]
现在官方已经支持了，新版本 v3 也已移除这个功能，并修复了其他问题，现在 Web Store 正在审核，你也可以在 [Releases 页](https://github.com/douyin-helper/douyin-helper/releases)下载最新版的 crx 文件手动安装。
