### ISSUE TITLE
麻烦增加下搜索不要在新窗口打开的功能

### ISSUE THREAD

**Issue by jocongmin** [douyin-helper/douyin-helper#39]
希望搜索在本窗口打开

**Comment by wildseeder** [comment]
新版本 v3 支持这个配置了，现在 Web Store 正在审核，估计还要等几天，你也可以在 [Releases 页](https://github.com/douyin-helper/douyin-helper/releases)下载最新版的 crx 文件手动安装。

**Comment by jocongmin** [comment]
您的邮件我已收到，谢谢。
