### ISSUE TITLE
能不能提供一键下载功能，能去水印更好

### ISSUE THREAD

**Issue by groundwater-modeling** [douyin-helper/douyin-helper#6]

**Comment by wildseeder** [comment]
小助手未来会提供快捷获取视频源地址的功能。
下载功能目前已经有其他专门的插件提供了，可以试试这个：[三品-抖音视频下载助手](https://chrome.google.com/webstore/detail/%E4%B8%89%E5%93%81-%E6%8A%96%E9%9F%B3%E8%A7%86%E9%A2%91%E4%B8%8B%E8%BD%BD%E5%8A%A9%E6%89%8B/oilijcpeckbjebkibcjfdmepacegnnpn)。

**Comment by groundwater-modeling** [comment]
> 小助手未来会提供快捷获取视频源地址的功能。 下载功能目前已经有其他专门的插件提供了，可以试试这个：[三品-抖音视频下载助手](https://chrome.google.com/webstore/detail/%E4%B8%89%E5%93%81-%E6%8A%96%E9%9F%B3%E8%A7%86%E9%A2%91%E4%B8%8B%E8%BD%BD%E5%8A%A9%E6%89%8B/oilijcpeckbjebkibcjfdmepacegnnpn)。

谢谢
